apiVersion: apps/v1
kind: Deployment
metadata:
  name: graafschap-www
  labels:
    app: graafschap-www
    tier: graafschap-www
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: graafschap-www
  template:
    metadata:
      labels:
        app: graafschap-www
        tier: graafschap-www
    spec:
      containers:
      - name: graafschap-frontend
        image: defjef/graafschap:0.1
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: graafschap-www-service
spec:
  selector:
    app: graafschap-www
  ports:
    - name: http
      port: 80
      targetPort: 80
