apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-graafschap-site
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: graafschap.defjef.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
           name: graafschap-service
           port: 
            number: 80
  - host: www.corsograafschap.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
           name: graafschap-service
           port: 
            number: 80